### ISSUE TITLE
[Sample code submission] Django example app

### ISSUE THREAD

**Issue by clemfromspace** [algolia-samples/about#18]
**What's the use case for the sample?**
This is a Django application indexing 500 Contact objects and providing auto-completion and instant-search samples.

**What's the programming language?**
Python, Javascript

**Sample GitHub URL:**
https://github.com/algolia/algoliasearch-django-example

**Author Information (please fill out):**

- Author name: Youcef Mammar
- Author GitHub Handle: https://github.com/tkrugg
- Organization name (if submitted on behalf of a company): Algolia
- Organization GitHub URL(if submitted on behalf of a company): github.com/algolia

**Dependencies:**
None

**Checklist:**

- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Algolia's [best practices coding guidelines](https://github.com/algolia-samples/about/tree/master/guidelines) for my sample
- [x] I agree and adhere to the [Code of Conduct](https://github.com/algolia-samples/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The sample has been authored by me / or my organization and will be kept up-to-date. If the sample will not longer be maintained, I'll notify this project.

**Comment by eunice** [comment]
Submission has been added to CodeX.
