### ISSUE TITLE
[Sample code submission] Autocomplete-powered GitHub notification filters

### ISSUE THREAD

**Issue by sarahdayan** [algolia-samples/about#19]
**What's the use case for the sample?**

This example shows a GitHub-like notification filtering panel.

**What's the programming language?**

TypeScript, React

**Sample GitHub URL:**
https://github.com/algolia/autocomplete/tree/next/examples/github-notification-filters

**Author Information (please fill out):**

- Author name: Sarah Dayan
- Author GitHub Handle: https://github.com/sarahdayan
- Organization name (if submitted on behalf of a company): Algolia
- Organization GitHub URL(if submitted on behalf of a company): https://github.com/algolia

**Dependencies:**
Autocomplete, React

**Checklist:**

- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Algolia's [best practices coding guidelines](https://github.com/algolia-samples/about/tree/master/guidelines) for my sample
- [x] I agree and adhere to the [Code of Conduct](https://github.com/algolia-samples/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The sample has been authored by me / or my organization and will be kept up-to-date. If the sample will not longer be maintained, I'll notify this project.

**Comment by eunice** [comment]
Submission has been added to CodeX.

**Comment by ozupey** [comment]
@sarahdayan thanks for your great work on this. 

Where can I find the JS files and documentation so I can start using this on my website?

**Comment by sarahdayan** [comment]
Hi @ozupey, if you click the first link in my PR description, you'll find the TypeScript project.

**Comment by ozupey** [comment]
> Hi @ozupey, if you click the first link in my PR description, you'll find the TypeScript project.

I'm aware of the TypeScript files, but this is not a language supported by browsers. I'm looking for the "dist" folder with the JS files so I can use this in my website. Or do you expect every user to download yarn, npm, and 229 MB worth of 1000+ dependencies just to be able to use this? :)

**Comment by sarahdayan** [comment]
@ozupey For now this demo only exists in TypeScript. It also uses JSX so even if it was using JavaScript, it would need to compiled before being usable in production.

You can generate a `dist` folder with compiled JavaScript files by cloning this priject locally (following the [demo's README](https://github.com/algolia/autocomplete/tree/next/examples/github-notification-filters#readme)) and running the `build` command, but keep in mind these would be compiled artifacts.

If you want source file in JavaScript, for now you'll need to either manually strip the TypeScript annotations from the demo, or do it using TypeScript's `tsc` command-line.

We fully understand that not all our users might want to deal with TypeScript, npm, or even JSX, and we'll keep that in mind for future demos. Thanks for bearing with us!
