### ISSUE TITLE
iOS examples bunch

### ISSUE THREAD

**Issue by VladislavFitz** [algolia-samples/about#26]
**What's the use case for the sample?**
- [Multi-index search](https://github.com/algolia/instantsearch-ios-examples/tree/master/Examples/MultiIndex)
- [Autocomplete with Voice search](https://github.com/algolia/instantsearch-ios-examples/tree/master/Examples/VoiceSearch)
- [Categories with Hits](https://github.com/algolia/instantsearch-ios-examples/tree/master/Examples/CategoriesHits)
- [Query Suggestions](https://github.com/algolia/instantsearch-ios-examples/tree/master/Examples/QuerySuggestions)
- [Query Suggestions with recent searches](https://github.com/algolia/instantsearch-ios-examples/tree/master/Examples/QuerySuggestionsRecentSearches)
- [Query Suggestions with Hits](https://github.com/algolia/instantsearch-ios-examples/tree/master/Examples/QuerySuggestionsHits)
- [Query Suggestions with Categories](https://github.com/algolia/instantsearch-ios-examples/tree/master/Examples/QuerySuggestionsCategories)

**What's the programming language?**
Swift

**Author Information:**

- Author name: Vladislav Fitc
- Author GitHub Handle: github.com/vladislavfitz
- Organization name: Algolia
- Organization GitHub URL: github.com/algolia

**Dependencies:**
- [InstantSearch iOS](https://github.com/algolia/instantsearch-ios)
- [SDWebImage](https://github.com/SDWebImage/SDWebImage)
- [Voice Overlay iOS](https://github.com/algolia/voice-overlay-ios)

**Checklist:**

- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Algolia's [best practices coding guidelines](https://github.com/algolia-samples/about/tree/master/guidelines) for my sample
- [x] I agree and adhere to the [Code of Conduct](https://github.com/algolia-samples/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The sample has been authored by me / or my organization and will be kept up-to-date. If the sample will not longer be maintained, I'll notify this project.

**Comment by eunice** [comment]
Submissions have been added to CodeX.
