### ISSUE TITLE
Kentico Xperience integration

### ISSUE THREAD

**Issue by kentico-ericd** [algolia-samples/about#34]
**What's the use case for the sample?**
Xperience is a CMS/DXP platform which mid-large companies use to develop websites. We have a search solution built-in, but we have recently added Algolia to our toolbox.

**What's the programming language?**
C#

**Sample GitHub URL:**
https://github.com/Kentico/xperience-algolia

**Author Information (please fill out):**

- Author name: Kentico
- Author GitHub Handle: https://github.com/Kentico
- Organization name (if submitted on behalf of a company): Kentico
- Organization GitHub URL(if submitted on behalf of a company): https://github.com/Kentico

**Dependencies:**

**Checklist:**

- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Algolia's [best practices coding guidelines](https://github.com/algolia-samples/about/tree/master/guidelines) for my sample
- [x] I agree and adhere to the [Code of Conduct](https://github.com/algolia-samples/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] The sample has been authored by me / or my organization and will be kept up-to-date. If the sample will not longer be maintained, I'll notify this project.

**Comment by clemfromspace** [comment]
Hey @kentico-ericd , thanks a lot for the contribution, and sorry for the late answer!
Your submission will be soon added to the code exchange!
