### ISSUE TITLE
React Demo Boilerplate

### ISSUE THREAD

**Issue by matthew1809** [algolia-samples/about#38]
**What's the use case for the sample?**
This sample shows the main features of Algolia in action.

**What's the programming language?**
ReactJS, Javascript

**GitHub URL:**
https://github.com/algolia/algolia-react-boilerplate

**Author Information (please fill out):**

- Author name: Matthew Foyle
- Author GitHub Handle: matthew1809
- Organization name (if submitted on behalf of a company): Algolia
- Organization GitHub URL(if submitted on behalf of a company): github.com/algolia

**Dependencies:**
N/A

**Checklist:**

> Please check every part of this checklist for us to process your request. You can do this by marking them with `[x]` instead of `[ ]`.

- [X] My sample application is open source and has a permissive license such as MIT or Apache-2
- [X] There are no known security vulnerabilities and I'm following security best practices
- [X] I've read Algolia's [best practices coding guidelines](https://github.com/algolia-samples/about/tree/master/guidelines) for my sample
- [X] I agree and adhere to the [Code of Conduct](https://github.com/algolia-samples/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] The sample has been authored by me / or my organization and will be kept up-to-date. If the sample will not longer be maintained, I'll notify this project.

**Comment by clemfromspace** [comment]
LGTM 👍
