### ISSUE TITLE
GraphQL schema generator

### ISSUE THREAD

**Issue by chuckmeyer** [algolia-samples/about#7]
**What's the use case for the sample?**
_Please explain what use case this sample is addressing. 
If your sample is an implementation of an existing sample in another programming language, please add a link to the existing sample here._

Given an Algolia index, generates valid GraphQL types for exposing a GraphQL backend search Query

**What's the programming language?**
_What's the primary programming language for this sample? If your sample has both front-end and back-end components, please list both._

TypeScript

**Sample GitHub URL:**
_Please list the GitHub URL of your project, for example, `github.com/algolia-samples/chatbot-with-algolia-answers`_

https://github.com/charlypoly/algolia-graphql-schema

**Author Information (please fill out):**

- Author name: Charly Poly
- Author GitHub Handle: github.com/charlypoly
- Organization name (if submitted on behalf of a company): N/A
- Organization GitHub URL(if submitted on behalf of a company): N/A

**Dependencies:**
_Please list any dependencies for services, tools, or others this project has, including Algolia's services. For example, Algolia Answers, Google Cloud Vision, etc._

`algoliasearch-client-javascript`

**Checklist:**

> Please check every part of this checklist for us to process your request. You can do this by marking them with `[x]` instead of `[ ]`.

- [x] My sample application is open source and has a permissive license such as MIT or Apache-2
- [x] There are no known security vulnerabilities and I'm following security best practices
- [x] I've read Algolia's [best practices coding guidelines](https://github.com/algolia-samples/about/tree/master/guidelines) for my sample
- [ ] I agree and adhere to the [Code of Conduct](https://github.com/algolia-samples/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] The sample has been authored by me / or my organization and will be kept up-to-date. If the sample will not longer be maintained, I'll notify this project.

**Comment by eunice** [comment]
Submission has been added to CodeX.
